### PR TITLE
Clean up the model

### LINKED ISSUE #1: Not able to execute the demo
Is this demo executable? I am getting 6 errors while running on simulator on XCODE 7.2.

### PR DESCRIPTION
**Pull request by ghost**
Refactored the model layer... I'd say it's more readable now. Let me know your thoughts @RuiAAPeres. This should also close #1 & #2.

### CODE REVIEW

**Comment by ghost** [comment]
Haha not feelin' the changes huh @RuiAAPeres? Care to elaborate?

**Comment by RuiAAPeres** [comment]
well, I think there is a disconnect between your "Clean up Model" and the actual changes you have. Or at least my interpretation of "Clean up Model" is different than what you present. It would be useful if you could separate each change as a single commit, so from the message I could evaluate the intent. Pushing a "blob" of changes with such a terse description, makes it difficult to evaluate the merit of the PR. You could potentially have very valuable/legit change, but it gets lost in the noise. 

For example the changes you did in `MVCDemo/AppDelegate.swift`. They touch your:

1. Updated to Swift 3.

But what else?

**Comment by ghost** [comment]
So all of the changes are naming changes, as opposed to actual architecture changes. The whole thing started as I was trying to walk someone through iOS's interpretation of MVC using your article. The article was useful in providing a high-level overview but when it came to the code... you just kinda get overwhelmed, fast. The fact that the app's use-case is quite trivial doesn't really help matters much. It already felt over-architected, especially if you're someone who's just learning. My solution was to abstract everything out even further but then apply consistent naming to the data-structures as well as the project's directory hierarchy.

You're right about my oversight vis-à-vis the 'blob' commit. I should have committed more often. To be honest, I wasn't planning on submitting a PR when I started. By the time I finished, I figured this repo is simple enough that — if it came down to it — you could just open the project in Xcode and easily assess the merit of its changes. I understand if that's not the case, though ☺️

**Comment by RuiAAPeres** [comment]
@MikiMik at the end of the day I am a spectator, can't really merge, or do anything about this PR, besides giving my opinion. 😛

**Comment by ghost** [comment]
Ah. I suspected but wasn't sure. I suppose I might as well tag @rwenderlich then? In any case, a .gitignore for .DS_Store and an update to Swift 3 should be merged. The target audience of your article is probably mostly newbies; it would facilitate their learning experience if they could simply clone the repo and get it working.

**Comment by RuiAAPeres** [comment]
> In any case, a .gitignore for .DS_Store and an update to Swift 3 should be merged.

👍

**Pull request closed without merging**
